name: MetaGame
main: no.runsafe.metagame.Plugin
version: 1.0.@BUILD@
authors: [mortenn,Kruithne]
description: A framework for building minigames in minecraft.
commands:
  game:
    description: A collection of commands for managing games.
